### ISSUE TITLE
Feature Request: additional feature for .attach

### ISSUE THREAD

**Issue by sapics** [ArminJo/ServoEasing#10]
Thanks for very useful library!

I would like to use `attach` as follows.
`.attach(pin, minPulse, maxPulse, degreeForMinPulse, degreeForMaxPulse)`
Because some of servos move range are not 180 degree.

If the below examples are possible, it looks very useful.
```c++
.attach(5, 500, 2500); // default values (0, 180) looks good.
.attach(5, 500, 2500, -60, 60);
.attach(5, 500, 2500, 90, -30);
```

**Comment by ArminJo** [comment]
Hi sapics,
the new feature is now available, please test it and give feedback.

**Comment by sapics** [comment]
Thank you very much ArminJo!

It looks great!
I ordered servo motors, and it will arrive in a few days.
I will make a test report as soon as possible!

**Comment by sapics** [comment]
It works well as I expected in Arduino UNO.
Thanks again!
