### ISSUE TITLE
Multiple servos using PCA 9685

### ISSUE THREAD

**Issue by MrBaddeley** [ArminJo/ServoEasing#16]
I have a question about the PCA9685. Basically I'm using the Adafruit library to directly control a number of servos (6) on a single board. I would like to switch into a automatic animation mode using your servo easing libray. If I'm using the wire & adafruit library to directly control, can I also load your to switch over to (using a toggle) or is it one or the other. 

Secondly, can I use the library over 6 servos as the example shows a single servo on the PCA9685?

**Comment by ArminJo** [comment]
You can use this library and e.g. the `Adafruit_PWMServoDriver` library concurrently to control your servos. Be aware that the PCA9685 expander is **reset** at the first `attach()` and **initialized** at every further `attach()`.
The example shows only 1 servo to figure out, that there is no difference between using the Expander or the Servo() interface. But it is tested with 3 expander boards :-)
