### ISSUE TITLE
Regulary crashes with ESP32/PCA9685, but never with ESP8266/PCA9685

### ISSUE THREAD

**Issue by jibeer** [ArminJo/ServoEasing#21]
### Arduino Platform
* [ ] Arduino ATmega328* board (UNO, Nano)
* [ ] Arduino ATmega2560 board (Mega)
* [ ] Arduino ATmega32U4 board (Leonardo)
* [ ] Arduino SAM board (Due)
* [ ] Arduino SAMD board (Zero, MKR*)
* [ ] ESP8266 board
* [X] ESP32 board
* [ ] STM32 board
* [ ] Other - please specify

### IDE
* [ ] Arduino IDE
* [ ] Arduino Pro IDE
* [ ] Sloeber IDE
* [ ] PlatformIO IDE
* [ ] Other

### Example expressing the bug
* [ ] Simple
* [ ] OneServo
* [ ] TwoServos
* [ ] AsymmetricEasing
* [ ] PCA9685_Expander
* [ ] PCA9685_ExpanderFor32Servos
* [ ] ContinuousRotatingServo
* [ ] Other

### Current behavior

Regulary crashes with ESP32/PCA9685, but never with ESP8266/PCA9685 (maybe when under stress...)
4 servos in use.
ROCK SOLID with ESP8266/PCA9685 !

**Comment by ArminJo** [comment]
Do you use the latest version?
What is the crash output?
Is one Servo moving before the crash?

**Comment by ArminJo** [comment]
With the current version and using areInterruptsActive() it works!

**Comment by jibeer** [comment]
Hello. Sorry not to be able to help more. But seems that you found the bug,
congrats. Let me say again that your library is awesome! Respect.
All the best!
