### ISSUE TITLE
No timer for Teensy 4.1

### ISSUE THREAD

**Issue by Eebel** [ArminJo/ServoEasing#23]
### Arduino Platform
* [ ] Arduino ATmega328* board (UNO, Nano)
* [ ] Arduino ATmega2560 board (Mega)
* [ ] Arduino ATmega32U4 board (Leonardo)
* [ ] Arduino SAM board (Due)
* [ ] Arduino SAMD board (Zero, MKR*)
* [ ] ESP8266 board
* [ ] ESP32 board
* [ ] STM32 board
* [x ] Other - please specify

### IDE
* [ ] Arduino IDE
* [ ] Arduino Pro IDE
* [ ] Sloeber IDE
* [ ] PlatformIO IDE
* [ x] Other

### Example expressing the bug
* [ ] Simple
* [ ] OneServo
* [ ] TwoServos
* [ ] AsymmetricEasing
* [x ] PCA9685_Expander
* [ ] PCA9685_ExpanderFor32Servos
* [ ] ContinuousRotatingServo
* [ ] Other

### Version
* [ x] Yes I use the latest version
* [ ] Other - please specify

### Current behavior

"No periodic timer support existent (or known) for this platform. Only blocking functions and simple example will run!"

**Comment by Eebel** [comment]
Using the Arduino IDE with the Teensyduino add-on.

**Comment by ArminJo** [comment]
I added a timer, but I can not test it. Please test the latest version from repository.

**Comment by Eebel** [comment]
Thanks, I’ll report.

Tim

Sent from my iPad

On Jun 12, 2020, at 21:04, Armin <notifications@github.com> wrote:

﻿

I added a timer, but I can not test it. Please test the latest version from repository.

**Comment by Eebel** [comment]
It works very nicely.

Thank you for keeping the best servo library up-to-date!  I absolutely love the power of these tools you have created.

Thank you,

Tim
________________________________
