### ISSUE TITLE
Serial Plotter does not plot anything in Arduino IDE 1.8.13

### ISSUE THREAD

**Issue by sbcalaff** [ArminJo/ServoEasing#27]
### Arduino Platform
* [X] Arduino ATmega328* board (UNO, Nano)
* [ ] Arduino ATmega2560 board (Mega)
* [ ] Arduino ATmega32U4 board (Leonardo)
* [ ] Arduino megaAVR board (NanoEvery)
* [ ] Arduino SAM board (Due)
* [ ] Arduino SAMD board (Zero, MKR*)
* [ ] ESP8266 board
* [ ] ESP32 board
* [ ] STM32 board
* [ ] Apollo3 board
* [ ] Teensy board
* [ ] Other - please specify

### IDE
* [X] Arduino IDE
* [ ] Arduino Pro IDE
* [ ] Sloeber IDE
* [ ] PlatformIO IDE
* [ ] Other - please specify

### Example to reproduce the issue
* [ ] Simple
* [ ] OneServo
* [ ] TwoServos
* [ ] AsymmetricEasing
* [ ] PCA9685_Expander
* [ ] PCA9685_ExpanderAndServo
* [ ] PCA9685_ExpanderFor32Servos
* [ ] ContinuousRotatingServo
* [X] Other

### Pin(s) used for servo, if not default
Default (9).

### Version
* [X] Yes I use the [latest release](https://github.com/ArminJo/ServoEasing/releases)
* [ ] Other - please specify

### Current behavior

`// Library
#include <ServoEasing.h>

// Create a servo object
ServoEasing servo_sg90;

// Execute once
void setup(void) {

  // Baud rate
  const unsigned long ulong_baud_rate = 115200;

  // Initialize the serial port
  Serial.begin(ulong_baud_rate);

  // Local constants
  const byte byte_digital_output_servo = 9;
  const unsigned long ulong_min = 600; // pulse width (µs) corresponding to 0º
  const unsigned long ulong_max = 2610; // pulse width (µs) corresponding to 180º

  // Attach the servo variable to a pin
  servo_sg90.attach(byte_digital_output_servo, ulong_min, ulong_max);

  // Go to the neutral position
  servo_sg90.write(90);

  // Wait until shaft stops
  delay(250); // speed: 0.12 s/60º (4.8 V) -> 0.36 s/180º (500 ms for security in vase 180º)

  // Set a default moving speed
  servo_sg90.setSpeed(40); // degrees per second

  // Set the moving type
  servo_sg90.setEasingType(EASE_SINE_IN_OUT);

}

// Execute in loop
void loop() {

  // Go to 45º at 180º per second
  servo_sg90.easeTo(45, 180); // int aDegree, uint_fast16_t aDegreesPerSecond

  // Go to angle 135º at 20º per second
  servo_sg90.easeTo(135, 20);  
  
}`

Although `#define PRINT_FOR_SERIAL_PLOTTER` is not commented in "ServoEasing.h", Serial Plotter does not plot anything. Serial Monitor does print the temporal evolution of the position.

### Expected behavior

Serial Plotter should plot the temporal evolution of the position of the shaft of the servomotor.

### Error output

Nothing is shown at the Serial Plotter.

**Comment by ArminJo** [comment]
Please check the baudrate of the plotter window
