### ISSUE TITLE
Error when install from Library Manager in Arduino IDE

### ISSUE THREAD

**Issue by brha** [ArminJo/ServoEasing#28]
## Bug Report
When clicking on "Install" button in the Library Manager, you get the message:
Error downloading http://downloads.arduino.cc/libraries/github.com/ArminJo/ServoEasing-2.3.2.zip

### IDE
* [x ] Arduino IDE
* [ ] Arduino Pro IDE
* [ ] Sloeber IDE
* [ ] PlatformIO IDE
* [ ] Other - please specify

**Comment by ArminJo** [comment]
Sorry, but it works for me.
