### ISSUE TITLE
Error from Google when downloading the zip-file

### ISSUE THREAD

**Issue by brha** [ArminJo/ServoEasing#29]
## Bug Report
When trying to download http://downloads.arduino.cc/libraries/github.com/ArminJo/ServoEasing-2.3.2.zip
Google showed this page:
https://support.google.com/chrome/answer/6261569?p=mixed_content_downloads&visit_id=637407656332908229-1942043711&rd=1&hl=en-GB
I could force the download, so I have the zip-file now.

**Comment by ArminJo** [comment]
Thanks for the info! 
But I cannot think of any reason for this, there are no scrips or similar contained.
BTW. Do you know that you can edit your issue, so you do not need to open a new one?
