### ISSUE TITLE
No support for the attiny85?

### ISSUE THREAD

**Issue by atomspring** [ArminJo/ServoEasing#31]
### Arduino Platform
* [ ] Arduino ATmega328* board (UNO, Nano)
* [ ] Arduino ATmega2560 board (Mega)
* [ ] Arduino ATmega32U4 board (Leonardo)
* [ ] Arduino megaAVR board (NanoEvery)
* [ ] Arduino SAM board (Due)
* [ ] Arduino SAMD board (Zero, MKR*)
* [ ] ESP8266 board
* [ ] ESP32 board
* [ ] STM32 board
* [ ] Apollo3 board
* [ ] Teensy board
* [X] Other - please specify

Board is an attiny85 (digispark)

### IDE
* [X] Arduino IDE
* [ ] Arduino Pro IDE
* [ ] Sloeber IDE
* [ ] PlatformIO IDE
* [ ] Other - please specify

### Example to reproduce the issue
* [ ] Simple
* [X] OneServo
* [ ] TwoServos
* [ ] AsymmetricEasing
* [ ] PCA9685_Expander
* [ ] PCA9685_ExpanderAndServo
* [ ] PCA9685_ExpanderFor32Servos
* [ ] ContinuousRotatingServo
* [ ] Other

### Pin(s) used for servo, if not default
Pin 0

### Version
* [X] Yes I use the [latest release](https://github.com/ArminJo/ServoEasing/releases)
* [ ] Other - please specify

### Current behavior
`#include <ServoEasing.h>

ServoEasing myservo;  // create servo object to control a servo

#define SERVO1_PIN 0  // Set t85 Pin 5 as servo pin

void setup() {
  myservo.attach(SERVO1_PIN);
  myservo.setEasingType(EASE_QUADRATIC_IN_OUT);
  myservo.easeTo(0);   // Set servo to 0
  delay(500);         // Wait 500ms for servo to reset
}

void loop() {
  myservo.startEaseToD(90,1000);
  delay(1200);
  myservo.startEaseToD(90,1000);
  while (areInterruptsActive()) {;}
}`

### Expected behavior
Compilation should succeed, with a servo sweeping back and forth

### Error output
`/home/atomspring/Documents/Projects/libraries/ServoEasing/src/ServoEasing.cpp: In function 'void enableServoEasingInterrupt()':
/home/atomspring/Documents/Projects/libraries/ServoEasing/src/ServoEasing.cpp:1184:5: error: 'TIFR1' was not declared in this scope
     TIFR1 |= _BV(OCF1B);    // clear any pending interrupts;
     ^~~~~
/home/atomspring/Documents/Projects/libraries/ServoEasing/src/ServoEasing.cpp:1184:5: note: suggested alternative: 'TIFR'
     TIFR1 |= _BV(OCF1B);    // clear any pending interrupts;
     ^~~~~
     TIFR
/home/atomspring/Documents/Projects/libraries/ServoEasing/src/ServoEasing.cpp:1185:5: error: 'TIMSK1' was not declared in this scope
     TIMSK1 |= _BV(OCIE1B);    // enable the output compare B interrupt
     ^~~~~~
/home/atomspring/Documents/Projects/libraries/ServoEasing/src/ServoEasing.cpp:1185:5: note: suggested alternative: 'TIMSK'
     TIMSK1 |= _BV(OCIE1B);    // enable the output compare B interrupt
     ^~~~~~
     TIMSK
/home/atomspring/Documents/Projects/libraries/ServoEasing/src/ServoEasing.cpp:1191:5: error: 'TCCR1B' was not declared in this scope
     TCCR1B |= _BV(ICNC1);
     ^~~~~~
/home/atomspring/Documents/Projects/libraries/ServoEasing/src/ServoEasing.cpp:1191:5: note: suggested alternative: 'TCCR0B'
     TCCR1B |= _BV(ICNC1);
     ^~~~~~
     TCCR0B
In file included from /home/atomspring/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino5/avr/include/avr/io.h:99:0,
                 from /home/atomspring/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino5/avr/include/avr/interrupt.h:38,
                 from /home/atomspring/.arduino15/packages/digistump/hardware/avr/1.7.0/cores/tiny/WProgram.h:8,
                 from /home/atomspring/.arduino15/packages/digistump/hardware/avr/1.7.0/cores/tiny/Arduino.h:4,
                 from /home/atomspring/Documents/Projects/libraries/ServoEasing/src/ServoEasing.cpp:31:
/home/atomspring/Documents/Projects/libraries/ServoEasing/src/ServoEasing.cpp:1191:19: error: 'ICNC1' was not declared in this scope
     TCCR1B |= _BV(ICNC1);
                   ^
/home/atomspring/Documents/Projects/libraries/ServoEasing/src/ServoEasing.cpp:1191:19: note: suggested alternative: 'CTC1'
/home/atomspring/Documents/Projects/libraries/ServoEasing/src/ServoEasing.cpp:1194:75: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     OCR1B = ((clockCyclesPerMicrosecond() * REFRESH_INTERVAL_MICROS) / 8) - 100;
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/home/atomspring/Documents/Projects/libraries/ServoEasing/src/ServoEasing.cpp: In function 'void disableServoEasingInterrupt()':
/home/atomspring/Documents/Projects/libraries/ServoEasing/src/ServoEasing.cpp:1306:5: error: 'TIMSK1' was not declared in this scope
     TIMSK1 &= ~(_BV(OCIE1B)); // disable the output compare B interrupt
     ^~~~~~
/home/atomspring/Documents/Projects/libraries/ServoEasing/src/ServoEasing.cpp:1306:5: note: suggested alternative: 'TIMSK'
     TIMSK1 &= ~(_BV(OCIE1B)); // disable the output compare B interrupt
     ^~~~~~
     TIMSK
Multiple libraries were found for "Servo.h"
 Used: /home/atomspring/Documents/Projects/libraries/Servo
 Not used: /usr/src/arduino-1.8.13/libraries/Servo
Using library ServoEasing at version 2.3.3 in folder: /home/atomspring/Documents/Projects/libraries/ServoEasing 
Using library Servo at version 1.1.7 in folder: /home/atomspring/Documents/Projects/libraries/Servo 
exit status 1
Error compiling for board Digispark.`

**Comment by ArminJo** [comment]
You are right, and in the current repo version you will see a better error message `This AVR CPU is not supported by ServoEasing`.
