### ISSUE TITLE
ESP8266 pin definitions

### ISSUE THREAD

**Issue by gmglickman** [ArminJo/ServoEasing#32]
### Arduino Platform
* [x] ESP8266 board

 * Platform         Servo1          Servo2        Servo3      Analog
 * -----------------------------------------------------------
 * ESP8266         14 // D5    12 // D6    13 // D7        0
 */

#if defined(ESP8266)
#define SERVO1_PIN 12 // D6
#define SERVO2_PIN 13 // D7
#define SERVO3_PIN 14 // D5

Shouldn't it be: 
SERVO1_PIN 14 // D5
SERVO2_PIN 12 // D6
SERVO3_PIN 13 // D7
to agree with the table?

**Comment by ArminJo** [comment]
Thanks for the feedback 🥇
