### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by botbuilder1** [ArminJo/ServoEasing#5]
I get an error compiling for a ESP32:

"This library only supports boards with an AVR, SAM, SAMD, NRF52 or STM32F4 processor."

Are there any plans on including the ESP32?

**Comment by ArminJo** [comment]
No one has asked for this before. For what purpose do you need it on the ESP32?

**Comment by veitk** [comment]
i didn't tried it yet but i also wanted to use this on the esp32 to replace the esp32servo lib.

this would be really awesome if you can support esp32 :)

**Comment by botbuilder1** [comment]
> No one has asked for this before. For what purpose do you need it on the ESP32?

The servo motion for my ice fishing jigger is so jerky.  Would LOVE to have that bounce built into it too.

TIA

**Comment by ArminJo** [comment]
OK let me have a look, if I can use the esp32servo lib on a ESP32.

**Comment by ArminJo** [comment]
OK guys, please download and test it.

**Comment by botbuilder1** [comment]
> OK guys, please download and test it.

Seems to work well, thanks!

**Comment by ArminJo** [comment]
Thanks, I now created a new release, so that the port may be soon available at the Arduino IDE.
