### ISSUE TITLE
Help with Bounce in my Code

### ISSUE THREAD

**Issue by ajkochev** [ArminJo/ServoEasing#52]
This isn't an issue really.  I would like to use your bounce function in my code to replace my bounceRun function.  I looked through the readme and opened a few examples but could not find one that uses the bounce.   Would it be possible to add an example that shows just how bounce works?

Everything works good just would like a little bounce when the movement finishes and what I wrote isn't very good.

Here is the code I have.  Everything works great.  Just want to replace my bounceRun function with something better.  Thank you for any help you can offer.

### Board
* [ ] Arduino ATmega328* board (UNO, Nano)

### IDE
* [ ] Arduino IDE

### Example to reproduce the issue
* [ ] PCA9685_Expander

### Version
* [ ] Yes I use the [latest repo version](https://github.com/ArminJo/ServoEasing/archive/master.zip) and verified this!

``
// C/MRI Model Railroad Semaphore Signal Controller for JMRI.

#include <Wire.h>
#include <Adafruit_PWMServoDriver.h>
#include <CMRI.h>
#include <Auto485.h>
#include <Servo.h>
#include <ServoEasing.h>

#define CMRI_ADDR 3  //CMRI Node address.  Change if needed.
#define DE_PIN    2  //Ardino pin (TX enable ?)
#define N_POS   3   //Three positions per servo.
#define N_SERVO 16  //number of servos possible on a single PCA9685 board.

Adafruit_PWMServoDriver pwm1 = Adafruit_PWMServoDriver (0x40);
Auto485 bus (DE_PIN);
CMRI cmri (CMRI_ADDR, 24, 48, bus);  // addr, # inp,  # out and bus speed
Servo Current_Servo;

// ------------------------------------------------

int currentServo;

/*
Below sets servoSteps array for each Servo to move at a time.  Increase for faster movement.
Set in multiples of 5 only.
First number is for servo on port 0 second for servo on port 1, etc.  */
int servoSteps [N_SERVO] = {5,5,5,5, 5,5,5,5, 5,5,5,5, 5,5,5,5};

/*
Below servoPeriod array sets the delay time between when the servo is moved using servoSteps.  
This is an additional way to slow down servo movement even further than if servoSteps was at 1.  
Increase values for slower movement.
First number is for servo on port 0 second for servo on port 1, etc.  Number is in miliseconds.*/
int servoPeriod[N_SERVO] = {30,30,30,30, 30,30,30,30, 30,30,30,30, 30,30,30,30};

/*
Below servoVal array sets the three position values used to set each servos positions.  
First three are for servo on port 0 second three for port 1, etc.
Set in multiples of 5 only.
Values must go from least to highest for the code to work properly this cannot be changed. 
Be sure the servo and armature are oriented properly to account for this before mounting on your layout.
To get values needed, run a calibration sketch on your servos before implimenting this sketch
To make a semaphore a two color/two position, put the same values in two of the three values.  
See port 8 below. */

enum { Min, Mid, Max };

int servoVal [N_SERVO][N_POS] = {
    { 800, 1050, 1250 },  // Port 0 servo on PCA9685 board.
    { 900, 1000, 1100 },
    { 900, 1000, 1100 },
    { 900, 1000, 1100 },

    { 900, 1000, 1100 },  // Port 4
    { 900, 1000, 1100 },
    { 900, 1000, 1100 },
    { 900, 1000, 1100 },

    { 900, 1200, 1200 },  // Port 8
    { 900, 1000, 1100 },
    { 900, 1000, 1100 },
    { 900, 1000, 1100 },

    { 900, 1000, 1100 },  // Port 12
    { 900, 1000, 1100 },
    { 900, 1000, 1100 },
    { 900, 1000, 1100 },
}; // end servoVal array

int  servoPos  [N_SERVO];  // Current servo position array.
int  servoTarg [N_SERVO];  // Target servo position array.

/*
Below startUpPos array sets the start up position of Semaphores.   
First three are for servo on port 0, second three are for port 1, etc.
Below example gives servo on port 0 the Mid position on Arduino start up.
Port 8 below example gives it the first on Min position.  
Be sure that each servo/port has only one 1 and the other two are 0.  */
bool startUpPos  [N_SERVO][N_POS]  =  {
    { 0, 1, 0 },  // Port 0 servo on PCA9685 board.
    { 0, 1, 0 },
    { 0, 1, 0 },
    { 0, 1, 0 },

    { 0, 1, 0 },  // Port 4
    { 0, 1, 0 },
    { 0, 1, 0 },
    { 0, 1, 0 },

    { 1, 0, 0 },  // Port 8
    { 0, 1, 0 },
    { 0, 1, 0 },
    { 0, 1, 0 },

    { 0, 1, 0 },  // Port 12
    { 0, 1, 0 },
    { 0, 1, 0 },
    { 0, 1, 0 },
};  //end startUpPos array

/*
Below arrays set the bouce wiggle after the semaphore is moved.
Set bounceOn[N_SERVO] to 1 to turn on bounce for that servo after it moves.
Set bounceStep[N_SERVO] to the size of the bounce you want, works similar to servoSteps above.
Set bouncePeriod[N_SERVO] to the delay of the bounce you want, works similar to servoPeriod above.
bouncePeriod[N_SERVO] is in milliseconds.
*/
bool bounceOn[N_SERVO]     = {1,0,0,0,     0,0,0,0,     1,0,0,0,     0,0,0,0};
int  bounceStep[N_SERVO]   = {20,5,5,5,    5,5,5,5,     20,5,5,5,    5,5,5,5};
int  bouncePeriod[N_SERVO] = {40,30,30,30, 30,30,30,30, 40,30,30,30, 30,30,30,30};

int  bounceNum  [N_SERVO];  // posible future use for number of times to run the bounce from side to side.

unsigned long msecLst;

// -----------------------------------------------------------------------------
void loop ()
{
    cmri.process ();

    for (int s = 0; s < N_SERVO; s++)  {
        Serial.print ("  ");
        for (int p = 0; p < N_POS; p++) {
            int bit = (s*N_POS) + p;
            if (cmri.get_bit (bit))  {
                servoTarg [s] = servoVal [s][p];
                currentServo = s;
                Serial.print (bit);
                break;      // on one position bit should be set
            }

        }
        Serial.print (" ");
        Serial.print (servoTarg [s]);
    }
    Serial.println ("");

    // adjust servos slowly
    unsigned long msec = millis ();
//#define Period  30
//#define Steps   5
    if ( (msec - msecLst) >= servoPeriod[currentServo])  {
        msecLst = msec;

        // adjust each servo toward target
        for (int s = 0; s < N_SERVO; s++)  {
            if (servoTarg [s] > servoPos [s]) {
                servoPos [s] += servoSteps[s];
                if (servoTarg [s] <= servoPos [s]) { // Done moving, set bounce type
                  servoPos  [s] = servoTarg [s];
                  if (bounceOn[s] = 1)  // bounceOn and BounceType must not be 0 to run the bounce
                    bounceRun(s, servoPos [s], 1);
                }
            }
            else if (servoTarg [s] < servoPos [s]) {
                servoPos [s] -= servoSteps[s];
                if (servoTarg [s] >= servoPos [s]) { // Done moving, set bounce type
                  servoPos  [s] = servoTarg [s];
                  if (bounceOn[s] = 1)  // bounceOn and BounceType must not be 0 to run the bounce
                    bounceRun(s, servoPos [s], 2);
                }
            }
            pwm1.writeMicroseconds (s, servoPos [s]);
            
            
        }
    }
}

// -----------------------------------------------------------------------------
void setup ()
{
    Serial.begin (19200);
    bus.begin (19200);
    pwm1.begin ();
    pwm1.setPWMFreq (50);

    for (int s = 0; s <= N_SERVO; s++) {
         for (int e = 0; e <= N_POS; e++) {
           if (startUpPos[s][e] == 1) {
             servoPos  [s] = servoVal[s][e];
             servoTarg [s] = servoVal[s][e];
             pwm1.writeMicroseconds (s, servoPos [s]);
           }
         }   
    }
}
// -----------------------------------------------------------------------------
void bounceRun (int curServo, int curPos, int typeMove)
{
    int m = curPos; int f = curPos;
    if (typeMove == 1)  {
      //Move two steps back
      delay(bouncePeriod[curServo]);
      m = m - bounceStep[curServo];
      pwm1.writeMicroseconds(curServo, m);
      delay(bouncePeriod[curServo]);
      m = m - bounceStep[curServo];
      pwm1.writeMicroseconds(curServo, m);
      //Move four steps forward
      delay(bouncePeriod[curServo]);
      m = m + bounceStep[curServo];
      pwm1.writeMicroseconds(curServo, m);
      delay(bouncePeriod[curServo]);
      m = m + bounceStep[curServo];
      pwm1.writeMicroseconds(curServo, m);
      delay(bouncePeriod[curServo]);
      m = m + bounceStep[curServo];
      pwm1.writeMicroseconds(curServo, m);
      delay(bouncePeriod[curServo]);
      m = m + bounceStep[curServo];
      pwm1.writeMicroseconds(curServo, m);
      //Move three steps back
      delay(bouncePeriod[curServo]);
      m = m - bounceStep[curServo];
      pwm1.writeMicroseconds(curServo, m);
      delay(bouncePeriod[curServo]);
      m = m - bounceStep[curServo];
      pwm1.writeMicroseconds(curServo, m);
      delay(bouncePeriod[curServo]);
      m = m - bounceStep[curServo];
      //Move two steps forward
      pwm1.writeMicroseconds(curServo, m);
      delay(bouncePeriod[curServo]);
      m = m + bounceStep[curServo];
      pwm1.writeMicroseconds(curServo, m);
      delay(bouncePeriod[curServo]);
      m = m + bounceStep[curServo];
      pwm1.writeMicroseconds(curServo, m);
    }
    if (typeMove == 2) {
      //Move two step forward                          
      delay(bouncePeriod[curServo]);
      m = m + bounceStep[curServo];
      pwm1.writeMicroseconds(curServo, m);
      delay(bouncePeriod[curServo]);
      m = m + bounceStep[curServo];
      pwm1.writeMicroseconds(curServo, m);
      //Move four steps back
      delay(bouncePeriod[curServo]);
      m = m - bounceStep[curServo];
      pwm1.writeMicroseconds(curServo, m);
      delay(bouncePeriod[curServo]);
      m = m - bounceStep[curServo];
      pwm1.writeMicroseconds(curServo, m);
      delay(bouncePeriod[curServo]);
      m = m - bounceStep[curServo];
      pwm1.writeMicroseconds(curServo, m);
      delay(bouncePeriod[curServo]);
      m = m - bounceStep[curServo];
      pwm1.writeMicroseconds(curServo, m);
      //Move three steps forward
      delay(bouncePeriod[curServo]);
      m = m + bounceStep[curServo];
      pwm1.writeMicroseconds(curServo, m);
      delay(bouncePeriod[curServo]);
      m = m + bounceStep[curServo];
      pwm1.writeMicroseconds(curServo, m);
      delay(bouncePeriod[curServo]);
      m = m + bounceStep[curServo];
      //Move two steps back
      pwm1.writeMicroseconds(curServo, m);
      delay(bouncePeriod[curServo]);
      m = m - bounceStep[curServo];
      pwm1.writeMicroseconds(curServo, m);
      delay(bouncePeriod[curServo]);
      m = m - bounceStep[curServo];
      pwm1.writeMicroseconds(curServo, m);
    }
    //Set final position to what is was at start of function
    pwm1.writeMicroseconds(curServo, f);
}

**Comment by ArminJo** [comment]
Just change easing type to Bounce like `Servo3.setEasingType(EASE_BOUNCE_OUT);` in the AsymmetricEasing example.

**Comment by ajkochev** [comment]
This is no help.  And I did look more into your code trying to make sense of it.   I still don’t understand how to put your code into mine when I need to move call my servos like this on a PCA9685 board:

 

pwm1.writeMicroseconds(curServo, m);

 

Closing the issue without asking if I was helped was rude as well.

**Comment by ArminJo** [comment]
Please use another library!
And you now what an issue is??? in contrast to an discussion???
