### ISSUE TITLE
Attach speed

### ISSUE THREAD

**Issue by Dario-Ciceri** [ArminJo/ServoEasing#92]
Would it be possible to set an initial speed so that attach does not bring the servo into position at full speed? In some projects there is a risk of breaking something and it would be better to bring the servos into position at low speeds, thank you.

**Comment by ArminJo** [comment]
You know how a servo works?
And how it is controlles basically?

**Comment by Dario-Ciceri** [comment]
> You know how a servo works? And how it is controlled basically?

yes, I checked your attach function and you can add an initial position, in your function you use write function and maybe that's why there's no speed settings for the attach command?

**Comment by ArminJo** [comment]
Great, you know how my software works.
But this was NOT the question.
Hint: https://github.com/ArminJo/ServoEasing#useful-resources

**Comment by Dario-Ciceri** [comment]
> Great, you know how my software works. But this was NOT the question. Hint: https://github.com/ArminJo/ServoEasing#useful-resources

I'm sorry but I don't understand what is the need to use certain tones, I just asked you a question and I know very well how a servo motor works, I use them for many projects besides the fact that I studied electronics... thanks anyway, I will edit the library...

**Comment by ArminJo** [comment]
Good luck, maybe you will win the nobel price for this.

**Comment by Dario-Ciceri** [comment]
> Good luck, maybe you will win the nobel price for this.

meanwhile you didn't answer my question, you could have used better tones but you preferred to answer me shitty, congratulations
